### ISSUE TITLE
wrong tableWidth while enabling rowSelection

### ISSUE THREAD

**Issue by CaptainJon** [varown/react-antd-column-resize#1]
may forgot to calculate the rowSelection column

**Comment by varown** [comment]
Get, I'll check.

**Comment by CaptainJon** [comment]
> 请参考下demo https://varown.github.io/react-antd-column-resize/components/use-antd-column-resize 最后一个示例 1、拖动只关心单个的column的宽度 2、整体宽度还是外部和table来控制 3、关于排序和筛选功能已经通过内部样式来进行控制
> 
> 或者把遇到的详细问题 或者样式错乱发我，我会及时修改 或者提交PR 共同开发 感谢

问题描述：多次拖动后，handler的位置和标尺线基本就错位了。因为rowSelection的宽度没有计算进去tableWidth，根源就是columns中没有这个自动生成的列，也就是说Hook中接收到的columns是不准确的，实际多了一个选择列。而实际代码在计算tableWidth的时候，只有存在列的情况下才会计算宽度。

[复现链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-877244?file=/App.tsx)

![20230821152917](https://github.com/varown/react-antd-column-resize/assets/51065061/dba7d470-0c94-4bd2-b1f5-c0cfd47b15bc)

**Comment by varown** [comment]
> > 请参考下demo https://varown.github.io/react-antd-column-resize/components/use-antd-column-resize 最后一个示例 1、拖动只关心单个的column的宽度 2、整体宽度还是外部和table来控制 3、关于排序和筛选功能已经通过内部样式来进行控制
> > 或者把遇到的详细问题 或者样式错乱发我，我会及时修改 或者提交PR 共同开发 感谢
> 
> 问题描述：多次拖动后，handler的位置和标尺线基本就错位了。因为rowSelection的宽度没有计算进去tableWidth，根源就是columns中没有这个自动生成的列，也就是说Hook中接收到的columns是不准确的，实际多了一个选择列。而实际代码在计算tableWidth的时候，只有存在列的情况下才会计算宽度。
> 
> [复现链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-877244?file=/App.tsx)
> 
> ![20230821152917](https://user-images.githubusercontent.com/51065061/261950609-dba7d470-0c94-4bd2-b1f5-c0cfd47b15bc.png)

我复现了这个问题，感谢你的指出，我会尽快修改

**Comment by CaptainJon** [comment]
> > > 请参考下demo https://varown.github.io/react-antd-column-resize/components/use-antd-column-resize 最后一个示例 1、拖动只关心单个的column的宽度 2、整体宽度还是外部和table来控制 3、关于排序和筛选功能已经通过内部样式来进行控制
> > > 或者把遇到的详细问题 或者样式错乱发我，我会及时修改 或者提交PR 共同开发 感谢
> > 
> > 
> > 问题描述：多次拖动后，handler的位置和标尺线基本就错位了。因为rowSelection的宽度没有计算进去tableWidth，根源就是columns中没有这个自动生成的列，也就是说Hook中接收到的columns是不准确的，实际多了一个选择列。而实际代码在计算tableWidth的时候，只有存在列的情况下才会计算宽度。
> > [复现链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-877244?file=/App.tsx)
> > ![20230821152917](https://user-images.githubusercontent.com/51065061/261950609-dba7d470-0c94-4bd2-b1f5-c0cfd47b15bc.png)
> 
> 我复现了这个问题，感谢你的指出，我会尽快修改

可能还有一些其他的情况，比如树表的渲染时，[链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-grlqkc?file=/App.tsx)，你看能否复现。你的源代码我已经看了，我也没想到好的办法目前。

**Comment by varown** [comment]
> > > > 请参考下demo https://varown.github.io/react-antd-column-resize/components/use-antd-column-resize 最后一个示例 1、拖动只关心单个的column的宽度 2、整体宽度还是外部和table来控制 3、关于排序和筛选功能已经通过内部样式来进行控制
> > > > 或者把遇到的详细问题 或者样式错乱发我，我会及时修改 或者提交PR 共同开发 感谢
> > > 
> > > 
> > > 问题描述：多次拖动后，handler的位置和标尺线基本就错位了。因为rowSelection的宽度没有计算进去tableWidth，根源就是columns中没有这个自动生成的列，也就是说Hook中接收到的columns是不准确的，实际多了一个选择列。而实际代码在计算tableWidth的时候，只有存在列的情况下才会计算宽度。
> > > [复现链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-877244?file=/App.tsx)
> > > ![20230821152917](https://user-images.githubusercontent.com/51065061/261950609-dba7d470-0c94-4bd2-b1f5-c0cfd47b15bc.png)
> > 
> > 
> > 我复现了这个问题，感谢你的指出，我会尽快修改
> 
> 可能还有一些其他的情况，比如树表的渲染时，[链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-grlqkc?file=/App.tsx)，你看能否复现。你的源代码我已经看了，我也没想到好的办法目前。

好的，这个在做的时候多个表头考虑了，但是这种情况属实没有考虑到，我看有没有好的解决办法

**Comment by varown** [comment]
> > > > > 请参考下demo https://varown.github.io/react-antd-column-resize/components/use-antd-column-resize 最后一个示例 1、拖动只关心单个的column的宽度 2、整体宽度还是外部和table来控制 3、关于排序和筛选功能已经通过内部样式来进行控制
> > > > > 或者把遇到的详细问题 或者样式错乱发我，我会及时修改 或者提交PR 共同开发 感谢
> > > > 
> > > > 
> > > > 问题描述：多次拖动后，handler的位置和标尺线基本就错位了。因为rowSelection的宽度没有计算进去tableWidth，根源就是columns中没有这个自动生成的列，也就是说Hook中接收到的columns是不准确的，实际多了一个选择列。而实际代码在计算tableWidth的时候，只有存在列的情况下才会计算宽度。
> > > > [复现链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-877244?file=/App.tsx)
> > > > ![20230821152917](https://user-images.githubusercontent.com/51065061/261950609-dba7d470-0c94-4bd2-b1f5-c0cfd47b15bc.png)
> > > 
> > > 
> > > 我复现了这个问题，感谢你的指出，我会尽快修改
> > 
> > 
> > 可能还有一些其他的情况，比如树表的渲染时，[链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-grlqkc?file=/App.tsx)，你看能否复现。你的源代码我已经看了，我也没想到好的办法目前。
> 
> 好的，这个在做的时候多个表头考虑了，但是这种情况属实没有考虑到，我看有没有好的解决办法

关于问题一 单选/多选 临时的解决方案是 columns 的第一个项先写 fixed: 'left',  先临时解决偏移的问题。后续的方案在整理

**Comment by varown** [comment]
> > > > > 请参考下demo https://varown.github.io/react-antd-column-resize/components/use-antd-column-resize 最后一个示例 1、拖动只关心单个的column的宽度 2、整体宽度还是外部和table来控制 3、关于排序和筛选功能已经通过内部样式来进行控制
> > > > > 或者把遇到的详细问题 或者样式错乱发我，我会及时修改 或者提交PR 共同开发 感谢
> > > > 
> > > > 
> > > > 问题描述：多次拖动后，handler的位置和标尺线基本就错位了。因为rowSelection的宽度没有计算进去tableWidth，根源就是columns中没有这个自动生成的列，也就是说Hook中接收到的columns是不准确的，实际多了一个选择列。而实际代码在计算tableWidth的时候，只有存在列的情况下才会计算宽度。
> > > > [复现链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-877244?file=/App.tsx)
> > > > ![20230821152917](https://user-images.githubusercontent.com/51065061/261950609-dba7d470-0c94-4bd2-b1f5-c0cfd47b15bc.png)
> > > 
> > > 
> > > 我复现了这个问题，感谢你的指出，我会尽快修改
> > 
> > 
> > 可能还有一些其他的情况，比如树表的渲染时，[链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-grlqkc?file=/App.tsx)，你看能否复现。你的源代码我已经看了，我也没想到好的办法目前。
> 
> 好的，这个在做的时候多个表头考虑了，但是这种情况属实没有考虑到，我看有没有好的解决办法

关于树形结构我仔细审核了你提供的代码 发现是使用错误
![image](https://github.com/varown/react-antd-column-resize/assets/62412197/c820a31a-c1ab-4e5c-aa85-727eebc479a2)
columns中必须有一项不能设置width，在提供的示例中有每一项都设置了

关于对选/单选的修改  已发送新的版本 1.0.1
再次感谢你的帮助和支持

**Comment by CaptainJon** [comment]
> > > > > > 请参考下demo https://varown.github.io/react-antd-column-resize/components/use-antd-column-resize 最后一个示例 1、拖动只关心单个的column的宽度 2、整体宽度还是外部和table来控制 3、关于排序和筛选功能已经通过内部样式来进行控制
> > > > > > 或者把遇到的详细问题 或者样式错乱发我，我会及时修改 或者提交PR 共同开发 感谢
> > > > > 
> > > > > 
> > > > > 问题描述：多次拖动后，handler的位置和标尺线基本就错位了。因为rowSelection的宽度没有计算进去tableWidth，根源就是columns中没有这个自动生成的列，也就是说Hook中接收到的columns是不准确的，实际多了一个选择列。而实际代码在计算tableWidth的时候，只有存在列的情况下才会计算宽度。
> > > > > [复现链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-877244?file=/App.tsx)
> > > > > ![20230821152917](https://user-images.githubusercontent.com/51065061/261950609-dba7d470-0c94-4bd2-b1f5-c0cfd47b15bc.png)
> > > > 
> > > > 
> > > > 我复现了这个问题，感谢你的指出，我会尽快修改
> > > 
> > > 
> > > 可能还有一些其他的情况，比如树表的渲染时，[链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-grlqkc?file=/App.tsx)，你看能否复现。你的源代码我已经看了，我也没想到好的办法目前。
> > 
> > 
> > 好的，这个在做的时候多个表头考虑了，但是这种情况属实没有考虑到，我看有没有好的解决办法
> 
> 关于树形结构我仔细审核了你提供的代码 发现是使用错误 ![image](https://user-images.githubusercontent.com/62412197/262570433-c820a31a-c1ab-4e5c-aa85-727eebc479a2.png) columns中必须有一项不能设置width，在提供的示例中有每一项都设置了
> 
> 关于对选/单选的修改 已发送新的版本 1.0.1 再次感谢你的帮助和支持

好的，单选的修改是怎么解决的，添加fixed么

**Comment by varown** [comment]
> > > > > > > 请参考下demo https://varown.github.io/react-antd-column-resize/components/use-antd-column-resize 最后一个示例 1、拖动只关心单个的column的宽度 2、整体宽度还是外部和table来控制 3、关于排序和筛选功能已经通过内部样式来进行控制
> > > > > > > 或者把遇到的详细问题 或者样式错乱发我，我会及时修改 或者提交PR 共同开发 感谢
> > > > > > 
> > > > > > 
> > > > > > 问题描述：多次拖动后，handler的位置和标尺线基本就错位了。因为rowSelection的宽度没有计算进去tableWidth，根源就是columns中没有这个自动生成的列，也就是说Hook中接收到的columns是不准确的，实际多了一个选择列。而实际代码在计算tableWidth的时候，只有存在列的情况下才会计算宽度。
> > > > > > [复现链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-877244?file=/App.tsx)
> > > > > > ![20230821152917](https://user-images.githubusercontent.com/51065061/261950609-dba7d470-0c94-4bd2-b1f5-c0cfd47b15bc.png)
> > > > > 
> > > > > 
> > > > > 我复现了这个问题，感谢你的指出，我会尽快修改
> > > > 
> > > > 
> > > > 可能还有一些其他的情况，比如树表的渲染时，[链接](https://codesandbox.io/s/ji-ben-shi-yong-forked-grlqkc?file=/App.tsx)，你看能否复现。你的源代码我已经看了，我也没想到好的办法目前。
> > > 
> > > 
> > > 好的，这个在做的时候多个表头考虑了，但是这种情况属实没有考虑到，我看有没有好的解决办法
> > 
> > 
> > 关于树形结构我仔细审核了你提供的代码 发现是使用错误 ![image](https://user-images.githubusercontent.com/62412197/262570433-c820a31a-c1ab-4e5c-aa85-727eebc479a2.png) columns中必须有一项不能设置width，在提供的示例中有每一项都设置了
> > 关于对选/单选的修改 已发送新的版本 1.0.1 再次感谢你的帮助和支持
> 
> 好的，单选的修改是怎么解决的，添加fixed么

现在不需要添加fixed了， 升级最新版本 就自动处理了。在计算width总和的时候做了处理，之前也做了容错处理只是处理的宽度不够。
