### ISSUE TITLE
Hook生效应当在文档中还加一个前提条件

### ISSUE THREAD

**Issue by CaptainJon** [varown/react-antd-column-resize#10]
添加文档注释：要使得列宽可以被拖动，除了要声明width属性外，必须声明key或dataIndex属性，否则拖动不生效。
因为有时候表格中的操作列不声明key或dataIndex也是可以的。
![image](https://github.com/varown/react-antd-column-resize/assets/51065061/1f0ae600-76aa-401f-bf6a-eaa5ef06dc89)

**Comment by varown** [comment]
好的 一会加上
