### ISSUE TITLE
应用该组件时拖拽的光标会自动与鼠标

### ISSUE THREAD

**Issue by douyuezhang** [varown/react-antd-column-resize#11]

**Comment by douyuezhang** [comment]
![image](https://github.com/varown/react-antd-column-resize/assets/78595451/040397f9-53d7-4ac3-9f50-5df1a345aaba)

**Comment by varown** [comment]
你好，有遇到问题吗 ？

**Comment by douyuezhang** [comment]
你好，在使用你的resize组件时出现了鼠标点击下去后提示块左移的情况，所以联系你想问下有什么属性可以处理这个问题？发自我的手机-------- 原始邮件 --------发件人： 盂清风 ***@***.***>日期： 2023年10月13日周五 14:18收件人： varown/react-antd-column-resize ***@***.***>抄送： Beall Dou ***@***.***>, State change ***@***.***>主    题： Re: [varown/react-antd-column-resize] 应用该组件时拖拽的光标会自动与鼠标 (Issue #11)
你好，有遇到问题吗 ？

**Comment by varown** [comment]
如果条件允许的话，期望可以提供截图和代码，感谢，这样方便排查
1、首先麻烦看下是不是Columns 中至少有一项保持没写width，

**Comment by varown** [comment]
初步看到的表现是 应该是所有的columns 都写了width

**Comment by douyuezhang** [comment]
谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月13日 15:55 |
| 收件人 | ***@***.***> |
| 抄送至 | Beall ***@***.***>、State ***@***.***> |
| 主题 | Re: [varown/react-antd-column-resize] 应用该组件时拖拽的光标会自动与鼠标 (Issue #11) |

初步看到的表现是 应该是所有的columns 都写了width

**Comment by douyuezhang** [comment]
好的，谢谢，等周一上班了我回去删掉一个试一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月13日 15:55 |
| 收件人 | ***@***.***> |
| 抄送至 | Beall ***@***.***>、State ***@***.***> |
| 主题 | Re: [varown/react-antd-column-resize] 应用该组件时拖拽的光标会自动与鼠标 (Issue #11) |

初步看到的表现是 应该是所有的columns 都写了width

**Comment by douyuezhang** [comment]
已点star,后期如果场景合适的话会推荐同事使用该组件，



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月13日 15:55 |
| 收件人 | ***@***.***> |
| 抄送至 | Beall ***@***.***>、State ***@***.***> |
| 主题 | Re: [varown/react-antd-column-resize] 应用该组件时拖拽的光标会自动与鼠标 (Issue #11) |

初步看到的表现是 应该是所有的columns 都写了width
