### ISSUE TITLE
当dataIndex为0的时候会有问题

### ISSUE THREAD

**Issue by Js-Man-H5** [varown/react-antd-column-resize#17]
![image](https://github.com/varown/react-antd-column-resize/assets/62057975/bbf63a77-431d-4456-a90f-b8a8300733a0)
这个判断不严谨，dataIndex为0的时候 他是不成立的 但实际他应该是成立的

**Comment by Js-Man-H5** [comment]
width 设置小于120 也有问题

**Comment by varown** [comment]
问题1 
正常情况下后端不会设置 flag值为key哦，如果大家有特殊需求可兼容。
问题2 
文档有写哦 有默认最小宽度的
![image](https://github.com/varown/react-antd-column-resize/assets/62412197/64387729-53e2-453f-a86f-c790a5ba2881)

**Comment by Js-Man-H5** [comment]
好的

**Comment by varown** [comment]
感谢支持！如有更好的建议可以自己提交PR
