### ISSUE TITLE
css 这么写嵌套打包编译通不过。这个怎么处理呢？

### ISSUE THREAD

**Issue by 738579138** [varown/react-antd-column-resize#18]
![image](https://github.com/varown/react-antd-column-resize/assets/18671263/1bfa7515-557e-481e-af14-19da1e87b5c0)

**Comment by varown** [comment]
你好，这边方便把报错放一下吗 感谢
1、方便我这边看下 看看怎么更好处理
2、或者看下你的wabpack 配置，对应预处理器是否有配置
