### ISSUE TITLE
拖拽手柄点击会有一个跳动的效果，这个是刻意做的吗，

### ISSUE THREAD

**Issue by finebo** [varown/react-antd-column-resize#21]
感谢提供的示例，
在示例的第二个tab里面光标放到 age 列后方的 拖拽柄上面，单击左键，age列的宽度会变宽，拖拽柄会向右侧跳动

**Comment by varown** [comment]
是的，不好意思给你带来误解了，参数有个默认的最小宽度，默认是120，如图所示我写的width是100，点击的时候会自动变成120
![image](https://github.com/varown/react-antd-column-resize/assets/62412197/04b429a9-2266-4baa-b2c7-e9b82326ec7b)
![image](https://github.com/varown/react-antd-column-resize/assets/62412197/f5142918-2df1-4402-87ef-dcb76c295fc5)

**Comment by finebo** [comment]
好的，谢谢，了解了，还有个在强类型校验下，导出的 resizableColumns 等几个参数会报类型错误，库里可以用any,或者泛型由使用者指定会更好些

**Comment by varown** [comment]
感谢指出，立马照办
