### ISSUE TITLE
columns里如果带有筛选项的话,会不显示 

### ISSUE THREAD

**Issue by 18336302495** [varown/react-antd-column-resize#25]
{
      title: "投放人",
      width: 150,
      dataIndex: ["promotion_link", "admin", "name"],
      filters: miniappfilters,
      onFilter: (value, record) => {
        return record.small_app?.name?.indexOf(value) === 0;
      },
    },

**Comment by long36708** [comment]
把 miniappfilters 放到useAntdColumnResize的依赖项里应该就可以了吧
