### ISSUE TITLE
该库使用了 sass，但是依赖并未声明导致运行失败

### ISSUE THREAD

**Issue by getatny** [varown/react-antd-column-resize#8]
Hi，

首先感谢您的开源项目。
但是在使用时发现该库使用了 sass 作为样式预处理器，并且没有将其声明到 package.json 中。
由于使用 father build 的 bundleless 模式，并未将 scss 后缀文件处理，所以在没有 sass 的项目中使用该库将会报错。

建议是否能将 sass 移除，或在 publish 前先用 sass 将 scss 文件转化为 css，又或者使用 jss 编写样式并将 jss 加入 dependencies。

再次感谢

**Comment by varown** [comment]
非常非常感谢你的指出，已经在修改，预期发布版本1.0.3
